import 'package:flutter/material.dart';
import 'package:tac/data/data/constants/app_colors.dart';

import '../../widhets/common widgets/buttons/myJob_card.dart';

// List of Dummy Job Data
class DummyJobCardData {
  static List<JobCardController> getDummyData() {
    return [
      JobCardController(
        jobTitle: 'Software Engineer',
        perHourRate: 'In Progress',
        companyName: 'Tech Corp',
        rating: '4.5',
        hiringTag: 'Urgent',
        jobType: 'Full-time',
        location: 'New York, NY',
        distance: '5 km away',
        day: 'Monday',
        shiftTime: '5 min remaining',
        requiredPersons: '2 required',
        jobDept: 'IT',
        jobStatus: Colors.green,
        showDetails: false,
        statusLabel: 'Active',
      ),
      JobCardController(
        jobTitle: 'UI/UX Designer',
        perHourRate: 'Awaiting',
        companyName: 'Design Studios',
        rating: '4.2',
        hiringTag: 'Hot',
        jobType: 'Part-time',
        location: 'Los Angeles, CA',
        distance: '8 km away',
        day: 'Tuesday',
        shiftTime: '1 hr remaining',
        requiredPersons: '1 required',
        jobDept: 'Design',
        jobStatus: Colors.orange,
        showDetails: false,
        statusLabel: 'Pending',
      ),
      JobCardController(
        jobTitle: 'UI/UX Designer',
        perHourRate: 'Awaiting',
        companyName: 'Design Studios',
        rating: '4.2',
        hiringTag: 'Hot',
        jobType: 'Part-time',
        location: 'Los Angeles, CA',
        distance: '8 km away',
        day: 'Tuesday',
        shiftTime: '1 hr remaining',
        requiredPersons: '1 required',
        jobDept: 'Design',
        jobStatus: Colors.orange,
        showDetails: false,
        statusLabel: 'Pending',
      ),
      JobCardController(
        jobTitle: 'QA Tester',
        perHourRate: '\$429.00',
        companyName: 'QualitySoft',
        rating: '4.7',
        hiringTag: 'Top Rated',
        jobType: 'Remote',
        location: 'Chicago, IL',
        distance: '3 km away',
        day: 'Friday',
        shiftTime: '12:00 AM - 8:00 PM',
        requiredPersons: '3 required',
        jobDept: 'QA',
        jobStatus: Colors.blue,
        showDetails: true,
        statusLabel: 'Completed',
      ),
      JobCardController(
        jobTitle: 'QA Tester',
        perHourRate: 'Cancelled',
        companyName: 'QualitySoft',
        rating: '4.7',
        hiringTag: 'Top Rated',
        jobType: 'Remote',
        location: 'Chicago, IL',
        distance: '3 km away',
        day: 'Friday',
        shiftTime: '12:00 AM - 8:00 PM',
        requiredPersons: '3 required',
        jobDept: 'QA',
        jobStatus: Colors.red,
        showDetails: true,
        statusLabel: 'Cancelled',
      ),
    ];
  }
}
