import 'package:flutter/material.dart';

import '../../widhets/common widgets/buttons/job_card.dart';

List<JobCard> jobList = const [
  JobCard(
    jobTitle: "Residential Security Guard",
    perHourRate: "\$28/hr",
    companyName: "Huge Jackman",
    rating: "5.00",
    hiringTag: "Urgent Hiring",
    jobType: "One-time",
    location: "Downtown Manhattan, NY",
    distance: "2.4 Km away",
    day: "Today",
    shiftTime: "9:00 AM - 5:00 PM",
    requiredPersons: "3 Required",
    jobDept: "Armed",
  ),
  JobCard(
    jobTitle: "Corporate Office Security",
    perHourRate: "\$32/hr",
    companyName: "Smith & Co.",
    rating: "4.8",
    hiringTag: "Immediate Join",
    jobType: "Full-time",
    location: "Brooklyn, NY",
    distance: "5 Km away",
    day: "Monday",
    shiftTime: "8:00 AM - 6:00 PM",
    requiredPersons: "5 Required",
    jobDept: "Corporate",
  ),
  JobCard(
    jobTitle: "Event Security Personnel",
    perHourRate: "\$25/hr",
    companyName: "EventSecure Ltd.",
    rating: "4.9",
    hiringTag: "Weekend Job",
    jobType: "Part-time",
    location: "Times Square, NY",
    distance: "3.2 Km away",
    day: "Saturday",
    shiftTime: "6:00 PM - 2:00 AM",
    requiredPersons: "10 Required",
    jobDept: "Event",
  ),
  JobCard(
    jobTitle: "Mall Security Officer",
    perHourRate: "\$30/hr",
    companyName: "City Mall Security",
    rating: "4.6",
    hiringTag: "Hiring Now",
    jobType: "Full-time",
    location: "Queens, NY",
    distance: "6 Km away",
    day: "Thursday",
    shiftTime: "10:00 AM - 8:00 PM",
    requiredPersons: "4 Required",
    jobDept: "Corporate",
  ),
  JobCard(
    jobTitle: "Nightclub Bouncer",
    perHourRate: "\$35/hr",
    companyName: "Elite Security",
    rating: "4.7",
    hiringTag: "Experienced Only",
    jobType: "Contract",
    location: "Las Vegas, NV",
    distance: "7 Km away",
    day: "Friday",
    shiftTime: "8:00 PM - 3:00 AM",
    requiredPersons: "2 Required",
    jobDept: "Event",
  ),
  JobCard(
    jobTitle: "Bank Security Guard",
    perHourRate: "\$33/hr",
    companyName: "Secure Bank Ltd.",
    rating: "4.9",
    hiringTag: "Armed Guard",
    jobType: "Permanent",
    location: "San Francisco, CA",
    distance: "1.5 Km away",
    day: "Tuesday",
    shiftTime: "7:00 AM - 5:00 PM",
    requiredPersons: "3 Required",
    jobDept: "Armed",
  ),
  JobCard(
    jobTitle: "VIP Bodyguard",
    perHourRate: "\$50/hr",
    companyName: "Elite Security Services",
    rating: "5.0",
    hiringTag: "Highly Trained",
    jobType: "Full-time",
    location: "Los Angeles, CA",
    distance: "10 Km away",
    day: "Wednesday",
    shiftTime: "24/7 Rotation",
    requiredPersons: "1 Required",
    jobDept: "Armed",
  ),
  JobCard(
    jobTitle: "Retail Store Security",
    perHourRate: "\$26/hr",
    companyName: "BestBuy Security",
    rating: "4.5",
    hiringTag: "Flexible Schedule",
    jobType: "Part-time",
    location: "Chicago, IL",
    distance: "4 Km away",
    day: "Sunday",
    shiftTime: "11:00 AM - 7:00 PM",
    requiredPersons: "5 Required",
    jobDept: "Corporate",
  ),
  JobCard(
    jobTitle: "Wedding Security",
    perHourRate: "\$22/hr",
    companyName: "Safe Events Co.",
    rating: "4.8",
    hiringTag: "Weekend Work",
    jobType: "One-time",
    location: "Houston, TX",
    distance: "2 Km away",
    day: "Saturday",
    shiftTime: "4:00 PM - 12:00 AM",
    requiredPersons: "6 Required",
    jobDept: "Event",
  ),
  JobCard(
    jobTitle: "Stadium Security",
    perHourRate: "\$28/hr",
    companyName: "Sports Arena Security",
    rating: "4.9",
    hiringTag: "Big Event",
    jobType: "Contract",
    location: "Miami, FL",
    distance: "8 Km away",
    day: "Sunday",
    shiftTime: "3:00 PM - 11:00 PM",
    requiredPersons: "15 Required",
    jobDept: "Event",
  ),
  JobCard(
    jobTitle: "Residential Armed Guard",
    perHourRate: "\$40/hr",
    companyName: "Safe Homes Ltd.",
    rating: "5.0",
    hiringTag: "Licensed Only",
    jobType: "Full-time",
    location: "Seattle, WA",
    distance: "3 Km away",
    day: "Monday",
    shiftTime: "6:00 AM - 2:00 PM",
    requiredPersons: "2 Required",
    jobDept: "Armed",
  ),
  JobCard(
    jobTitle: "Airport Security Officer",
    perHourRate: "\$38/hr",
    companyName: "SkySafe Security",
    rating: "4.7",
    hiringTag: "Federal Clearance",
    jobType: "Permanent",
    location: "Atlanta, GA",
    distance: "5 Km away",
    day: "Thursday",
    shiftTime: "4:00 AM - 12:00 PM",
    requiredPersons: "10 Required",
    jobDept: "Corporate",
  ),
  JobCard(
    jobTitle: "Concert Security Team",
    perHourRate: "\$24/hr",
    companyName: "Music Fest Protection",
    rating: "4.6",
    hiringTag: "Urgent Hiring",
    jobType: "Part-time",
    location: "Dallas, TX",
    distance: "4.5 Km away",
    day: "Saturday",
    shiftTime: "5:00 PM - 1:00 AM",
    requiredPersons: "12 Required",
    jobDept: "Event",
  ),
  JobCard(
    jobTitle: "Warehouse Night Security",
    perHourRate: "\$29/hr",
    companyName: "Logistics Security Co.",
    rating: "4.8",
    hiringTag: "Night Shift",
    jobType: "Full-time",
    location: "Phoenix, AZ",
    distance: "6 Km away",
    day: "Friday",
    shiftTime: "10:00 PM - 6:00 AM",
    requiredPersons: "4 Required",
    jobDept: "Corporate",
  ),
  JobCard(
    jobTitle: "School Security Guard",
    perHourRate: "\$27/hr",
    companyName: "Safe Schools Inc.",
    rating: "4.9",
    hiringTag: "Day Shift",
    jobType: "Full-time",
    location: "Philadelphia, PA",
    distance: "3.5 Km away",
    day: "Monday",
    shiftTime: "7:00 AM - 4:00 PM",
    requiredPersons: "3 Required",
    jobDept: "Corporate",
  ),
  JobCard(
    jobTitle: "Celebrity Close Protection",
    perHourRate: "\$55/hr",
    companyName: "VIP Protection Ltd.",
    rating: "5.0",
    hiringTag: "Elite Training",
    jobType: "Contract",
    location: "Beverly Hills, CA",
    distance: "9 Km away",
    day: "Tuesday",
    shiftTime: "Flexible",
    requiredPersons: "1 Required",
    jobDept: "Armed",
  ),
];
//
// import 'package:flutter/material.dart';
// import 'package:get/get.dart';
//
// import '../../widhets/common widgets/buttons/myJob_card.dart';

// class DummyJobCardData {
//   static List<JobCardController> getDummyData() {
//     return [
//       JobCardController(
//         jobTitle: 'Software Engineer',
//         perHourRate: '\$50/hr',
//         companyName: 'Tech Corp',
//         rating: '4.5',
//         hiringTag: 'Urgent',
//         jobType: 'Full-time',
//         location: 'New York, NY',
//         distance: '5 miles',
//         day: 'Monday',
//         shiftTime: '9:00 AM - 5:00 PM',
//         requiredPersons: '2',
//         jobDept: 'IT',
//         jobStatus: Colors.green,
//       ),
//       JobCardController(
//         jobTitle: 'Product Manager',
//         perHourRate: '\$60/hr',
//         companyName: 'Innovate Ltd.',
//         rating: '4.2',
//         hiringTag: 'Immediate Start',
//         jobType: 'Part-time',
//         location: 'San Francisco, CA',
//         distance: '3 miles',
//         day: 'Tuesday',
//         shiftTime: '10:00 AM - 3:00 PM',
//         requiredPersons: '1',
//         jobDept: 'Management',
//         jobStatus: Colors.blue,
//       ),
//       JobCardController(
//         jobTitle: 'Data Scientist',
//         perHourRate: '\$80/hr',
//         companyName: 'DataGen',
//         rating: '4.8',
//         hiringTag: 'Urgent',
//         jobType: 'Full-time',
//         location: 'Austin, TX',
//         distance: '8 miles',
//         day: 'Wednesday',
//         shiftTime: '9:00 AM - 6:00 PM',
//         requiredPersons: '3',
//         jobDept: 'Data',
//         jobStatus: Colors.orange,
//       ),
//       JobCardController(
//         jobTitle: 'Web Developer',
//         perHourRate: '\$40/hr',
//         companyName: 'Webify',
//         rating: '4.3',
//         hiringTag: 'Hiring Now',
//         jobType: 'Contract',
//         location: 'Los Angeles, CA',
//         distance: '7 miles',
//         day: 'Thursday',
//         shiftTime: '9:00 AM - 5:00 PM',
//         requiredPersons: '2',
//         jobDept: 'Development',
//         jobStatus: Colors.red,
//       ),
//       JobCardController(
//         jobTitle: 'UI/UX Designer',
//         perHourRate: '\$45/hr',
//         companyName: 'Creative Studio',
//         rating: '4.6',
//         hiringTag: 'Immediate Start',
//         jobType: 'Full-time',
//         location: 'Chicago, IL',
//         distance: '10 miles',
//         day: 'Friday',
//         shiftTime: '9:00 AM - 6:00 PM',
//         requiredPersons: '2',
//         jobDept: 'Design',
//         jobStatus: Colors.purple,
//       ),
//       JobCardController(
//         jobTitle: 'Network Engineer',
//         perHourRate: '\$55/hr',
//         companyName: 'NetWorks',
//         rating: '4.7',
//         hiringTag: 'Urgent',
//         jobType: 'Full-time',
//         location: 'Dallas, TX',
//         distance: '6 miles',
//         day: 'Monday',
//         shiftTime: '8:00 AM - 4:00 PM',
//         requiredPersons: '2',
//         jobDept: 'Engineering',
//         jobStatus: Colors.green,
//       ),
//       JobCardController(
//         jobTitle: 'Marketing Manager',
//         perHourRate: '\$65/hr',
//         companyName: 'BrandReach',
//         rating: '4.1',
//         hiringTag: 'Hiring Now',
//         jobType: 'Part-time',
//         location: 'Miami, FL',
//         distance: '4 miles',
//         day: 'Tuesday',
//         shiftTime: '9:00 AM - 3:00 PM',
//         requiredPersons: '1',
//         jobDept: 'Marketing',
//         jobStatus: Colors.blue,
//       ),
//       JobCardController(
//         jobTitle: 'Sales Representative',
//         perHourRate: '\$35/hr',
//         companyName: 'SalesForce',
//         rating: '3.9',
//         hiringTag: 'Immediate Start',
//         jobType: 'Full-time',
//         location: 'Seattle, WA',
//         distance: '12 miles',
//         day: 'Wednesday',
//         shiftTime: '8:00 AM - 5:00 PM',
//         requiredPersons: '5',
//         jobDept: 'Sales',
//         jobStatus: Colors.yellow,
//       ),
//       JobCardController(
//         jobTitle: 'Database Administrator',
//         perHourRate: '\$70/hr',
//         companyName: 'DB Solutions',
//         rating: '4.4',
//         hiringTag: 'Urgent',
//         jobType: 'Contract',
//         location: 'Denver, CO',
//         distance: '9 miles',
//         day: 'Thursday',
//         shiftTime: '9:00 AM - 5:00 PM',
//         requiredPersons: '2',
//         jobDept: 'IT',
//         jobStatus: Colors.orange,
//       ),
//       JobCardController(
//         jobTitle: 'Business Analyst',
//         perHourRate: '\$75/hr',
//         companyName: 'FinTech Co.',
//         rating: '4.9',
//         hiringTag: 'Immediate Start',
//         jobType: 'Full-time',
//         location: 'Boston, MA',
//         distance: '3 miles',
//         day: 'Friday',
//         shiftTime: '9:00 AM - 6:00 PM',
//         requiredPersons: '1',
//         jobDept: 'Business',
//         jobStatus: Colors.green,
//       ),
//     ];
//   }
// }
